### ISSUE TITLE
tiny formatting thing

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/bmenu#1]
Congrats! What a great piece of software!
I just wanted to let you know about a tiny little cosmetic formatting thing:
"> Configuration > Setup" has one space too many after Disk utility.
Apart from that the displayed title ::Settings:: differs from the actual menu entry on the above level "Configuration"
Keep up your beautiful work! :)

**Comment by oberon-manjaro** [comment]
Oh. I only get it now that the individual menu titles are obviously independent of the more explanatory menu entries above. Fine! :)

**Comment by Chrysostomus** [comment]
Fixed now
