### ISSUE TITLE
feature request: show current state in config menu options

### ISSUE THREAD

**Issue by Boruch-Baum** [Chrysostomus/bmenu#10]
In bmenu, when choosing the shell or the display manager, it would be helpful were there some indication of the current state, ie which shell or display manager was currently configured.

The operating environment is the manjaro 15.12 liveCD  for 686 using openRC and i3.

**Comment by Chrysostomus** [comment]
Done.

**Comment by Boruch-Baum** [comment]
Talk about speedy!

On 01/03/2016 11:06 PM, Chrysostomus wrote:

> Done.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/10#issuecomment-168576372

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
