### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by papajoker** [Chrysostomus/bmenu#14]
in system-setup file
for detect DM, dm_detect(): 

```
systemctl cat display-manager.service | awk -F'/' '/^Exec/ {print $NF}'
```

or use instead of status : show

```
systemctl show sddm | grep "State=enabled"
```

---

in initmenu file, config_editor()
is very bab to edit this files ! show them yes, but do not use sudo. For change/edit systemd configurations use sub-folders for overwrite

```
journald.conf.d/*.conf
logind.conf.d/*.conf
coredump.conf.d/*.conf
system.conf.d/*.conf
```

---

other : 
in this line https://github.com/Chrysostomus/bmenu/blob/master/bin/system-setup#L247  edit **slim** for config sddm ?

**Comment by Chrysostomus** [comment]
Thanks for the ideas!

Could you elaborate your idea about using .d subfolders?

**Comment by papajoker** [comment]
`man journald.conf.d` 

> can install configuration snippets in  /usr/lib/systemd/*.conf.d/.

is the same as `/etc/sysctl.d/` or `/etc/systemd/system/*.d`
- for don't have .pacnew use systemd/*.conf.d/ directory
- if user change original file .conf ,  this change may not be used if it is rewritten in the subdirectory conf.d/

I do not see too how to handle this for a user edit, but it is possible to list files in /XXX.conf.d/. And display a text saying to make these edits in this directory.

```
cat /etc/systemd/journald.conf.d/*.conf 
[Journal]
#voir le journald en temps réel dans console tty3
#ForwardToConsole=yes
#TTYPath=/dev/tty3
#MaxLevelConsole=notice
[Journal]
#niveau minimum à enregistrer
#MaxLevelStore=notice
MaxLevelStore=info
[Journal]
# taille du journald est de 250M réparti en 5 fichiers de 50Mo
SystemMaxUse=250M
SystemMaxFileSize=50M


 find  /etc/systemd/journald.conf.d/ -name "*.conf"
 /etc/systemd/journald.conf.d/journald-tty3.conf
 /etc/systemd/journald.conf.d/size.conf
 /etc/systemd/journald.conf.d/level.conf



cat /etc/systemd/coredump.conf.d/*.conf
[Coredump]
Storage=none
```

**Comment by Chrysostomus** [comment]
Implemented suggestions.
