### ISSUE TITLE
goes to network without asking permission first

### ISSUE THREAD

**Issue by Boruch-Baum** [Chrysostomus/bmenu#7]
bmenu, when selecting 1 for hardware, or 2 for display, surprisingly goes to the network to synchronize the package database, and then asks me whether I want to install, and all that without asking for permission in advance or telling me what it wants to install

**Comment by Chrysostomus** [comment]
It runs sudo pacman -Sy {mhwd-tui,brandr}. If it does not ask for permission, you must have ran bmenu as root or done something weird in your sudoers file. I'll add notification of what it is doing.

**Comment by Chrysostomus** [comment]
There is now notification

**Comment by Boruch-Baum** [comment]
No, on both counts. I just launched the LiveCD and it logged me in.
Never ran a root shell; never needed to sudo. I was just performing a
basic evaluation of the distro, not messing with it.

On 01/03/2016 10:56 PM, Chrysostomus wrote:

> It runs sudo pacman -Sy {mhwd-tui,brandr}. If it does not ask for permission, you must have ran bmenu as root or done something weird in your sudoers file. I'll add notification of what it is doing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/7#issuecomment-168575629

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
