### ISSUE TITLE
unable to use option 6 (network config)

### ISSUE THREAD

**Issue by Boruch-Baum** [Chrysostomus/bmenu#8]
bmenu. when selecting 6 for network gets response "wrong option" in red, followed by "wait and try again later".

The operating environment is the manjaro 15.12 liveCD  for 686 using openRC and i3.

**Comment by Chrysostomus** [comment]
Option relies on systemd at the moment.

**Comment by Boruch-Baum** [comment]
Understood. BTW, I'm in the middle of writing a bug report about the
inoperability of suspend, or even shutdown(!). My best guess has been to
direct the report to Ingo Burk at his github page. Would you know if
that's the wrong address?

On 01/03/2016 09:46 PM, Chrysostomus wrote:

> Option relies on systemd at the moment.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/8#issuecomment-168568650

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Chrysostomus** [comment]
The issue should be fixed now (in github, not in manjaro repos yet). There is now support for openrc in the option.

**Comment by oberon-manjaro** [comment]
Great, thank you! Let me know when you're ready to have it packed up! ;)

**Comment by Chrysostomus** [comment]
Soon, need to update system-setup forst too

**Comment by Boruch-Baum** [comment]
Thanks for the work, and for keeping me updated.

On 01/06/2016 08:37 AM, Chrysostomus wrote:

> The issue should be fixed now (in github, not in manjaro repos yet). There is now support for openrc in the option.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/8#issuecomment-169324139

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
