### ISSUE TITLE
unable to use option "toggle dark theme"

### ISSUE THREAD

**Issue by Boruch-Baum** [Chrysostomus/bmenu#9]
In bmenu, selecting 4 for appearance, and then 5 for toggle dark theme, gets response "unknown option" in red, followed by "wait and try again later"

The operating environment is the manjaro 15.12 liveCD  for 686 using openRC and i3.

**Comment by Chrysostomus** [comment]
I cannot reproduce the issue. It works for me. I need more details. Make sure you are running the latest version.

**Comment by Boruch-Baum** [comment]
The date on my iso is 12-30-2015, and I see on the sourceforge site that
the iso is dated 01-01-2016. I can download it again if you say that's a
new version, and not just some technicality new build.

On 01/03/2016 10:54 PM, Chrysostomus wrote:

> I cannot reproduce the issue. It works for me. I need more details. Make sure you are running the latest version.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/9#issuecomment-168575494

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Chrysostomus** [comment]
Downloading the iso again should make no difference. Run sudo pacman -Syu in the live session to get the lastest version. Or use the script in github. Just copy paste it into /usr/bin/appearance-menu to test.

**Comment by Boruch-Baum** [comment]
Hi. I just kind of screwed up on this (getting the new version of
bmenu), but there still may be data in my experience of use for you.

I installed (again) the manjaro-i3-openrc spin, but I ended up using the
same iso from January 2, so I didn't get the new version of bmenu that
way. When I updated the system using pacman -Syu, bmenu was not on the
update list. Just in case I over-looked something, the output to pacman
-Qo /usr/bin/appearance-menu is bmenu 0.4.1-4. To triple check, I
manually looked in the cache directory. So, if the update made it into
the new version of the iso, its somehow not yet in the repository or the
mirrors.

Before I hit send, I realized I wasn't sure which mirror I was using,
and you might want to know that. Sure enough, I hadn't known to run
rankmirrors -g, and the first mirror on the list was in Africa (Zambia).

Afterwards, the mirror was a more sensible dacentec.com. I then ran
pacman -Syyu, but there were no other updates for bmenu.

So, if the update is in the new iso, its doesn't seem to yet be in the repo.

To be clear: for me this is absolutely NOT urgent at all. I'm just
passing the info for the greater glory of manjaro rah rah rah hooray etc.

On 01/06/2016 08:38 AM, Chrysostomus wrote:

> Downloading the iso again should make no difference. Run sudo pacman -Syu in the live session to get the lastest version. Or use the script in github. Just copy paste it into /usr/bin/appearance-menu to test.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/9#issuecomment-169324642

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Chrysostomus** [comment]
Okay, thanks for testing!
Your version should be up to date then.
Can you post the contents of your /usr/bin/appearance-menu?

**Comment by oberon-manjaro** [comment]
Toggle dark theme doesn't work for me either, @Chrysostomus 
Btw the instruction displayed is not correct: It says "Select a number and press [Enter]".
Actually, Enter is not required. All numbers in ::Appearance:: work directly for me. 5 does nothing, but pressing 5 followed by Enter indeed gives

```
Unknown option 
Wait and try again later...
```

**Comment by Chrysostomus** [comment]
Aah, need to change that. 

In what way does the option not work? Does it not alter the setting file?

**Comment by oberon-manjaro** [comment]
It does not do anything obvious. Which setting file exactly do you mean?

**Comment by Chrysostomus** [comment]
$HOME/.config/gtk-3.0/settings.ini
It should alter the line
gtk-application-prefer-dark-theme=1
Changeing the number between 1 and 0.

**Comment by Chrysostomus** [comment]
Aah, you don't have that line?

**Comment by Chrysostomus** [comment]
I changed it so that it adds that line if it is missing.

**Comment by oberon-manjaro** [comment]
Exactly, that was the case. Also I just realized that there were some other zeros after I had played around with the Appearance section of bmenu... And I had ended up with font-name and font-size!!!! 0 everywhere. It was impossible to read anything in lxappearance or mousepad. I had to fix it with nano ... :laughing:

**Comment by oberon-manjaro** [comment]
Is bmenu by any chance changing the selection to zero when you don't select anything but abort? Font-name for example??

**Comment by Chrysostomus** [comment]
Should not change. It should change to empty if you abort in the font selection phase...

**Comment by oberon-manjaro** [comment]
Would it be possible to leave the settings untouched until you select something different? I think that's what you'd expected... ;)

**Comment by Boruch-Baum** [comment]
On 01/08/2016 10:54 AM, Chrysostomus wrote:

> Okay, thanks for testing!
> Your version should be up to date then.
> Can you post the contents of your /usr/bin/appearance-menu?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Chrysostomus/bmenu/issues/9#issuecomment-170038065
> 
> FYI the mtime on the file is 2015-12-29 01:29:48

It is an improvement in that menu traversal works.

However:
1] As in another menu I mentioned, the current selection state of themes
(gtk2/3) isn't listed.
2] It would be nice to always know which was the default (oops which
themes were the default, please. no joke)
3] I'm not sure any of it works. I've been toggling between all kind of
combinations in no particular order and I don't see any change to
pcmanfm or gpicview or qpdfview. I've been expecting the change to occur
immediately after setting the change as in other environments - is there
some other step to be taken with i3/bmenu for the changes to take effect.
4] Adding the line "gtk-application-prefer-dark-theme=1" to the config
file doesn't seem to help any

Here goes with the file /usr/bin/appearance-menu:

#!/bin/bash

RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'

if ! [ -f "$HOME/.gtkrc-2.0" ]; then
    cat > $HOME/.gtkrc-2.0 <<EOL
include "$HOME/.gtkrc-2.0.mine"
gtk-theme-name="Adwaita"
gtk-icon-theme-name="Adwaita"
gtk-font-name="DejaVu Sans 12"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=18
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintmedium"
gtk-xft-rgba="none"
EOL
fi

if ! [ -f "$HOME/.config/gtk-3.0/settings.ini" ]; then
    cat > $HOME/.config/gtk-3.0/settings.ini <<EOL
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=Adwaita
gtk-icon-theme-name=Adwaita
gtk-font-name=DejaVu Sans 12
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=18
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=none
gtk-decoration-layout=:menu,appmenu,close
EOL
fi

if ! [ -f "$HOME/.icons/default/index.theme" ]; then
    mkdir -r $HOME/.icons/default/
    cat > $HOME/.icons/default/index.theme <<EOL

# This file is written by LXAppearance. Do not edit.

[Icon Theme]
Name=Default
Comment=Default Cursor Theme
Inherits=Adwaita
EOL
fi

function set_gtk2_theme {
    new_theme="$@"
    cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep
"gtk-theme-name" .gtkrc-2.0)/gtk-theme-name=\"$new_theme\"/g" .gtkrc-2.0
}

function choose_gtk2_theme {
PS3="Choose new gtk2 theme: "

# Gather the results in an array.

gtk2_themes=($(find /usr/share/themes -type d -name "gtk-2.0" | awk
-F'/' '{print $5}') "proceed" "cancel")

select pick in "${gtk2_themes[@]}"
do
    case $pick in
        proceed)
            break
            ;;
        cancel)
            exit
            ;;  
        *)  
            picks+=("$pick")
            break
            ;;  
    esac
done

if [[ $picks ]]; then
    printf 'Setting theme to %s\n' "${picks[*]}"
    set_gtk2_theme "${picks[@]}"
    picks=()
fi
}

function set_gtk3_theme {
    new_theme="$@"
    cp $HOME/.config/gtk-3.0/settings.ini
$HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep
"gtk-theme-name"
$HOME/.config/gtk-3.0/settings.ini)/gtk-theme-name=$new_theme/g"
$HOME/.config/gtk-3.0/settings.ini
}

function choose_gtk3_theme {
PS3="Choose new gtk3 theme: "

# Gather the results in an array.

gtk3_themes=($(find /usr/share/themes -type d -name "gtk-3.0" | awk
-F'/' '{print $5}') "proceed" "cancel")

select pick in "${gtk3_themes[@]}"
do
    case $pick in
        proceed)
            break
            ;;
        cancel)
            exit
            ;;  
        *)  
            picks+=("$pick")
            break
            ;;  
    esac
done

if [[ $picks ]]; then
    printf 'Setting theme to %s\n' "${picks[*]}"
    set_gtk3_theme "${picks[@]}"
    picks=()
fi
}

function set_icon_theme {
    new_theme="$@"
    cp $HOME/.config/gtk-3.0/settings.ini
$HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep
"gtk-icon-theme-name"
$HOME/.config/gtk-3.0/settings.ini)/gtk-icon-theme-name=$new_theme/g"
$HOME/.config/gtk-3.0/settings.ini
    cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep
"gtk-icon-theme-name"
$HOME/.gtkrc-2.0)/gtk-icon-theme-name=\"$new_theme\"/g" $HOME/.gtkrc-2.0  
}

function choose_icon_theme {
PS3="Choose new icon theme: "

# Gather the results in an array.

icon_themes=($(find /usr/share/icons -type f -name "index.theme" | awk
-F'/' '{print $5}') "proceed" "cancel")

select pick in "${icon_themes[@]}"
do
    case $pick in
        proceed)
            break
            ;;
        cancel)
            exit
            ;;  
        *)  
            picks+=("$pick")
            break
            ;;  
    esac
done

if [[ $picks ]]; then
    printf 'Setting theme to %s\n' "${picks[*]}"
    set_icon_theme "${picks[@]}"
    picks=()
fi
}

function set_pointer_theme {
    new_theme="$@"
    cp $HOME/.icons/default/index.theme
$HOME/.icons/default/index.theme.bak && sed -i "s/$(grep "Inherits"
$HOME/.icons/default/index.theme)/Inherits=$new_theme/g"
$HOME/.icons/default/index.theme
    cp $HOME/.config/gtk-3.0/settings.ini
$HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep
"gtk-cursor-theme-name"
$HOME/.config/gtk-3.0/settings.ini)/gtk-cursor-theme-name=$new_theme/g"
$HOME/.config/gtk-3.0/settings.ini
    cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep
"gtk-cursor-theme-name"
$HOME/.gtkrc-2.0)/gtk-cursor-theme-name=\"$new_theme\"/g" $HOME/.gtkrc-2.0
}

function choose_pointer_theme {
PS3="Choose new pointer theme: "

# Gather the results in an array.

pointer_themes=($(find /usr/share/icons -type d -name "cursors" | awk
-F'/' '{print $5}' | sed 's/-Cursor//g') "proceed" "cancel")

select pick in "${pointer_themes[@]}"
do
    case $pick in
        proceed)
            break
            ;;
        cancel)
            exit
            ;;  
        *)  
            picks+=("$pick")
            break
            ;;  
    esac
done

if [[ $picks ]]; then
    printf 'Setting theme to %s\n' "${picks[*]}"
    set_pointer_theme "${picks[@]}"
    picks=()
fi
}

function set_font {
    new_theme="$@"
    cp $HOME/.config/gtk-3.0/settings.ini
$HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep
"gtk-font-name"
$HOME/.config/gtk-3.0/settings.ini)/gtk-font-name=$new_theme/g"
$HOME/.config/gtk-3.0/settings.ini
    cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep
"gtk-font-name" $HOME/.gtkrc-2.0)/gtk-font-name=\"$new_theme\"/g"
$HOME/.gtkrc-2.0  
}

function choose_font {
new_font=$(fc-list : family | tr , \n | fzf -e --reverse --prompt="<
Choose new font to use >")
echo "  Input the size of the font"
read font_size

set_font $new_font $font_size
}
function toggle_dark_theme {
    grep -q "gtk-application-prefer-dark-theme=1"
$HOME/.config/gtk-3.0/settings.ini && \
    sed -i
"s/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g"
$HOME/.config/gtk-3.0/settings.ini || \
    sed -i
"s/gtk-application-prefer-dark-theme=0/gtk-application-prefer-dark-theme=1/g"
$HOME/.config/gtk-3.0/settings.ini
}

function main {
    while true; do
    clear
    echo ""
    echo -e "                              ::Appearance::  "
    echo -e "
┌────────────────────────────────────────────────────────────────┐"
    echo -e " │    1   Set gtk2 theme               2   Set gtk3 theme
       │"
    echo -e " │    3   Set font                     4   Set icon theme
       │"
    echo -e " │    5   Toggle dark theme            6   Set pointer
theme      │"
    echo -e " │    7   Edit gtk2 settings           8   Edit gtk3
settings     │"
    echo -e " │    9   Edit Xresources              0   Exit
       │"
    echo -e "
└────────────────────────────────────────────────────────────────┘"
        echo -e "             Select a number and press [Enter] "
    echo ""
    read -s -n1 choix
    case $choix in
        1)
            echo
            choose_gtk2_theme
            echo ""
            ;;
        2)
            echo
            choose_gtk3_theme
            echo ""
            ;;
        3)
            echo
            choose_font
            echo ""
            ;;
        4)
            echo
            choose_icon_theme
            echo ""
            ;;
        5)
            echo
            toggle_dark_theme
            echo ""
            ;;
        6)
            echo
            choose_pointer_theme
            echo ""
            ;;
        7)
            echo
            nano $HOME/.gtkrc-2.0
            echo ""
            ;;
        8)
            echo
            nano $HOME/.config/gtk-3.0/settings.ini
            echo ""
            ;;
        9)
            echo
            nano $HOME/.Xresources
            echo ""
            ;;
        0)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Unknown option $NC"
            echo "Wait and try again later..."
            echo ""
            sleep 3
            clear
            ;;
    esac
    done
}

main

## 

hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
